name: Playwright Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # This forces Node.js 24
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd playwright
          npm ci

      - name: Install Playwright browsers
        run: |
          cd playwright
          npx playwright install

      - name: Run Playwright tests
        run: |
          cd playwright
          npx playwright test